{
 "title": "Zeek Cluster Health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Zeek Cluster",
    "query": "label_values(zeek_start_time_seconds{exported_type=\"plugin_start_time\"}, zeek_cluster)"
   },
   {
    "name": "node",
    "label": "Node Type",
    "query": "label_values(zeek_start_time_seconds{exported_type=\"plugin_start_time\", zeek_cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time/second",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(zeek_total_cpu_time_seconds{zeek_cluster=\"$cluster\", exported_type=\"cpu_time\", node!~\".*logger\"}[$__interval])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Process Restarts",
   "type": "graph",
   "description": "How many restarts has each process had?",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count(zeek_start_time_seconds{exported_type=\"plugin_start_time\", zeek_cluster=\"$cluster\"}) by (node), \"node\", \"$1\", \"node\", \".*(manager|logger|proxy|worker-.*)$\")",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Max Connections/s",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Max Logs/s",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeek_log_writes_total{zeek_cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Max Function Calls/s",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeek_function_calls_total{zeek_cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "max(rate(zeek_total_cpu_time_seconds{zeek_cluster=\"$cluster\", exported_type=\"cpu_time\", node!~\".*logger\"}[$__interval])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Log & Event Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Log Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "wps", "label": "lines/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeek_log_writes_total{exported_type=~\"log_(write|writer)\", writer=\"Log::WRITER_ASCII\", zeek_cluster=\"$cluster\"}[$__interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "cps", "label": "calls/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_function_calls_total{function_type=\"event\", zeek_cluster=\"$cluster\", name=~\".+\"}[$__interval])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Instantaneous Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Rate",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(5, sum(irate(zeek_log_writes_total{exported_type=~\"log_(write|writer)\", writer=\"Log::WRITER_ASCII\", zeek_cluster=\"$cluster\"}[$__interval])) by (path)))",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "Function Rate",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum(irate(zeek_function_calls_total{function_type!=\"event\", zeek_cluster=\"$cluster\", name=~\".+\"}[$__interval])) by (name)))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Event Rate",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(irate(zeek_function_calls_total{function_type=\"event\", zeek_cluster=\"$cluster\", name=~\".+\"}[$__interval])) by (name))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Script Profiling: Function Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Top Function by Invocations ($node)",
   "type": "graph",
   "description": "Top 20 functions that are being called. This is filtered by the \"node type\" variable at the top of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "cps", "label": "Function Calls/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_function_calls_total{function_type!=\"event\", zeek_cluster=\"$cluster\", name=~\".+\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Top Function Paths ($node)",
   "type": "graph",
   "description": "This tracks which function was called, and what the parent function was.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "cps", "label": "Function Path Calls/s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_function_calls_total{function_type!=\"event\", zeek_cluster=\"$cluster\", name=~\".+\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (name, function_caller))",
     "legendFormat": "{{ function_caller }} -> {{ name }}"
    }
   ]
  },
  {
   "title": "Script Profiling: Function Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Top BIFs by Time ($node)",
   "type": "graph",
   "description": "Top 10 Built-In Functions (\"BIFs\") by the amount of time spent executing them. This is filtered by the \"node type\" variable at the top of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "repeat": "node",
   "yaxes": [
    { "format": "s", "label": "Function Call Rate (Log)" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_cpu_time_per_function_seconds{function_type=\"built-in function\", zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Top Script-Land Functions by Time ($node)",
   "type": "graph",
   "description": "Top 10 script-land functions (including hooks, but excluding events) by the amount of time spent executing them. This is filtered by the \"node type\" variable at the top of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "repeat": "node",
   "yaxes": [
    { "format": "s", "label": "Function Call Rate (Log)" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_cpu_time_per_function_seconds{function_type=~\"(script-land function|hook)\", zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Script Profiling: Event Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Top Events by Time ($node)",
   "type": "graph",
   "description": "Top 10 events by the amount of time spent executing them. This is filtered by the \"node type\" variable at the top of the dashboard.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
   "repeat": "node",
   "yaxes": [
    { "format": "µs", "label": "Function Call Rate (Log)" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(zeek_cpu_time_per_function_seconds{function_type=\"event\", zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Weirds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Weirds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeek_function_calls_total{name=~\".*weird\", arg!=\"unknown_protocol\", zeek_cluster=\"$cluster\", arg=~\".+\"}[$__interval])) by (arg)",
     "legendFormat": "{{ arg }}"
    }
   ]
  },
  {
   "title": "Unknown Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(sum(rate(zeek_function_calls_total{name=\"net_weird\", arg=\"unknown_protocol\", zeek_cluster=\"$cluster\"}[$__interval])) by (addl), \"addl\", \"RSVP\", \"addl\", \"^46$\"), \"addl\", \"PIM\", \"addl\", \"^103$\"), \"addl\", \"IGMP\", \"addl\", \"^2$\"), \"addl\", \"SCTP\", \"addl\", \"^132$\"), \"addl\", \"ESP\", \"addl\", \"^50$\"), \"addl\", \"EGP\", \"addl\", \"^8$\")",
     "legendFormat": "{{ addl }}"
    }
   ]
  },
  { "title": "SumStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "SumStats by Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeek_function_calls_total{name=~\"SumStats.*\", zeek_cluster=\"$cluster\", arg=~\".+\"}[$__interval])) by (arg)",
     "legendFormat": "{{ arg }}"
    }
   ]
  },
  {
   "title": "SumStats by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "SumStats:: Function Calls" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(zeek_function_calls_total{name=~\"SumStats::.*\", zeek_cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(rate(zeek_function_calls_total{name=~\"SumStats::.*\", zeek_cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Traffic Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "New Connections by Worker (% drift)",
   "type": "graph",
   "description": "Perfectly balanced would have each worker at 0%.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent of New Connections" }
   ],
   "targets": [
    {
     "expr": "(1/scalar(count (zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}))) - rate(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}[$__interval])/scalar(sum(rate(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}[$__interval])))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "New Connections by System (% drift)",
   "type": "graph",
   "description": "Perfectly balanced would have each system at 0%.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "Percent of New Connections" }
   ],
   "targets": [
    {
     "expr": "(1/scalar(count (count by (box) (label_replace(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}, \"box\", \"$1\", \"instance\", \"(.*):.*\"))))) - (sum by (box) (label_replace(rate(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}[$__interval]), \"box\", \"$1\", \"instance\", \"(.*):.*\")))/scalar(sum(rate(zeek_function_calls_total{name=\"new_connection\", zeek_cluster=\"$cluster\"}[$__interval])))",
     "legendFormat": "{{ box }}"
    }
   ]
  },
  {
   "title": "Log Writes by Worker (% drift)",
   "type": "graph",
   "description": "Perfectly balanced would have each worker at 0%.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent of New Connections" }
   ],
   "targets": [
    {
     "expr": "(1/scalar(count (zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}))) - rate(zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}[$__interval])/scalar(sum(rate(zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}[$__interval])))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Log Writes by System (% drift)",
   "type": "graph",
   "description": "Perfectly balanced would have each system at 0%.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "Percent of New Connections" }
   ],
   "targets": [
    {
     "expr": "(1/scalar(count (count by (box) (label_replace(zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}, \"box\", \"$1\", \"instance\", \"(.*):.*\"))))) - (sum by (box) (label_replace(rate(zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}[$__interval]), \"box\", \"$1\", \"instance\", \"(.*):.*\")))/scalar(sum(rate(zeek_function_calls_total{name=\"Log::__write\", zeek_cluster=\"$cluster\", node!~\"(manager|logger|proxy)\"}[$__interval])))",
     "legendFormat": "{{ box }}"
    }
   ]
  },
  { "title": "Runtimes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Plugin Runtime by Hook ($node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "repeat": "node",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", plugin!=\"ESnet::Zeek_Exporter\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (hook) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "{{ hook }}"
    },
    {
     "expr": "sum(rate(zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", plugin=\"ESnet::Zeek_Exporter\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) by (hook, plugin) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "{{ hook }} (Plugin: {{ plugin }})"
    }
   ]
  },
  {
   "title": "Total Runtime by Function Type ($node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "repeat": "node",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "Plugin Hook"
    },
    {
     "expr": "sum(rate(zeek_cpu_time_per_function_type_seconds{zeek_cluster=\"$cluster\", function_type=\"built-in function\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "BIFs"
    },
    {
     "expr": "sum(rate(zeek_cpu_time_per_function_type_seconds{zeek_cluster=\"$cluster\", function_type=~\"(event|hook|script-land function)\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "Scripts"
    },
    {
     "expr": "sum(rate(zeek_total_cpu_time_seconds{zeek_cluster=\"$cluster\", exported_type=\"cpu_time\", node=~\".*[[node]][-0-9]*$\"}[$__interval])) / scalar(count(count by (node) (zeek_hook_cpu_time_seconds{zeek_cluster=\"$cluster\", node=~\".*[[node]][-0-9]*$\"})))",
     "legendFormat": "Total CPU Runtime"
    },
    { "expr": "1", "legendFormat": "Total" }
   ]
  }
 ]
}